python .\fixture_parser.py .\M_Nat_Fours_2025-32.pdf .\data\M_Nat_Fours.gz
python .\fixture_parser.py .\M_Nat_Pairs_2025-29.pdf .\data\M_Nat_Pairs.gz
python .\fixture_parser.py .\M-Indoor-Pairs-2025-36.pdf .\data\M-Indoor-Pairs.gz
python .\fixture_parser.py .\Mixed-Triples-2025-25.pdf .\data\Mixed-Triples.gz
python .\fixture_parser.py .\M-Nat-Indoor-Singles-2025-70.pdf .\data\M-Nat-Indoor-Singles.gz
python .\fixture_parser.py .\W_Nat_Fours_2025-27.pdf .\data\W_Nat_Fours.gz
python .\fixture_parser.py .\W_Nat_Pairs_2025-29.pdf .\data\W_Nat_Pairs.gz
python .\fixture_parser.py .\W-Indoor-Pairs-2025-38.pdf .\data\W-Indoor-Pairs.gz
python .\fixture_parser.py .\W-Nat-Indoor-Singles-2025-67.pdf .\data\W-Nat-Indoor-Singles.gz
python .\fixture_parser.py .\M-Nat-Singles-2025-32.pdf .\data\M-Nat-Singles.gz
python .\fixture_parser.py .\W-Nat-Singles-2025-34.pdf .\data\W-Nat-Singles.gz
python .\fixture_parser.py .\M_Nat_Triples_2024-29.pdf .\data\M_Nat_Triples.gz
python .\fixture_parser.py .\W_Nat_Triples_2024-31.pdf .\data\W_Nat_Triples.gz
python .\fixture_parser.py .\M_Novice_Singles_2025-35.pdf .\data\M_Novice_Singles.gz
python .\fixture_parser.py .\W_Novice_Singles_2025-31.pdf .\data\W_Novice_Singles.gz
python .\fixture_parser.py .\M-Novice-Pairs-2025-8.pdf .\data\M-Novice-Pairs.gz
python .\fixture_parser.py .\W-Novice-Pairs-2025-8.pdf .\data\W-Novice-Pairs.gz
python .\fixture_parser.py .\M-2x4x2-Pairs-2024-32.pdf .\data\M-2x4x2-Pairs.gz
python .\fixture_parser.py .\W-2x4x2-Pairs-2024-33.pdf .\data\W-2x4x2-Pairs.gz