FROM python:3.12-slim

WORKDIR /app

# Set timezone to Hong Kong
ENV TZ=Asia/Hong_Kong

COPY ./ExtractLBA_Files.py .
COPY ./fixture_parser.py .

RUN apt-get update && apt-get install -y cron openssh-client \
    && pip install --no-cache-dir paramiko requests bs4 \
        urllib3 pdfplumber tabulate \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# create a wrapper script to run the python scripts
RUN echo '#!/bin/bash\ncd /app\nPATH=$PATH:/usr/local/bin;export PATH\n/usr/local/bin/python /app/ExtractLBA_Files.py' > /app/run_extraction.sh && \
    chmod +x /app/run_extraction.sh

# Add the cron job
RUN echo "10,40 10-19 * * 1-5 /app/run_extraction.sh >> /var/log/cron.log 2>&1" | crontab -

RUN touch /var/log/cron.log

RUN mkdir /app/downloads /app/data /app/archive /app/local_data \
    && chmod 700 /root/.ssh

COPY ./privatekey /root/.ssh/privatekey
RUN chmod 600 /root/.ssh/privatekey
RUN echo "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
RUN chmod 600 /root/.ssh/config

CMD cron && tail -f /var/log/cron.log

